Numpy Tutorial: Creating Arrays
Array of Transportation
https://www.python-course.eu/numpy_create_arrays.php

In [86]:
import numpy as np
import transformations as tf

a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
x = range(1, 10)
print(x)
print(list(x))


range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
x  = np.arange(0.6, 10.4, 0.8)
print(x)


[ 0.6  1.4  2.2  3.   3.8  4.6  5.4  6.2  7.   7.8  8.6  9.4 10.2]


In [54]:
B = np.array([
    [0,2,1],
    [0,1,0],
    [1,0,-1]
])

tB = B.transpose()
print('tB')
print(tB)

v = np.array([3,-2,-5])
column = v.reshape((3, 1))


c = np.matmul(tB, column)
print('\ntB * column')
print(c)


tB
[[ 0  0  1]
 [ 2  1  0]
 [ 1  0 -1]]

tB * column
[[-5]
 [ 4]
 [ 8]]


In [85]:
def dot(u, v):
    for coord1, coord2 in zip(u,v):
        pass
        #print(coord1, coord2)
    
    #print('\n')
    
    el = [coord1 * coord2 for coord1, coord2 in zip(u,v)]
    #print(el)
    
    return sum(el)



def multiply_matrix_vector(matrix, vector):
    return tuple( dot(row, vector) for row in matrix)

B = (
    (0,2,1),
    (0,1,0),
    (1,0,-1)
)

v = (3,-2, 5)

Bv = multiply_matrix_vector(B, v)
print('\nBv')
print(Bv)




Bv
(1, -2, -2)


In [95]:
v = [1, 4, 6]
tX = tf.translation_matrix([3, 0, 0])
print(tX)

print(tX[:3,:3].T)

v1 = np.dot(tX[:3,:3].T, v)
print(v1)

[[1. 0. 0. 3.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 4. 6.]


In [111]:
v03 = np.array([0, 0, 1])
TL = np.array([
    [1, 0, 0, 3,],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]]
)

v04 = np.array([0, 0, 1, 1])

v14 = np.dot(TL, v04)
print('v14:')
print(v14)

#v13 = v14 - v14[4, 4]

v1:
[3 0 1 1]
